#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/opt/uppoint-cloud/scripts/lib/env-reader.sh
source "${SCRIPT_DIR}/lib/env-reader.sh"

ENV_FILE="/opt/uppoint-cloud/.env"
DATABASE_URL="${DATABASE_URL:-}"

if [ -z "$DATABASE_URL" ]; then
  DATABASE_URL="$(read_env_value "$ENV_FILE" "DATABASE_URL")"
fi

if [ -z "$DATABASE_URL" ]; then
  echo "[security-slo] DATABASE_URL is not set." >&2
  exit 1
fi

SECURITY_SLO_LOOKBACK_MINUTES="${SECURITY_SLO_LOOKBACK_MINUTES:-}"
SECURITY_SLO_MAX_LOGIN_OTP_FAILED="${SECURITY_SLO_MAX_LOGIN_OTP_FAILED:-}"
SECURITY_SLO_MAX_PASSWORD_RESET_FAILED="${SECURITY_SLO_MAX_PASSWORD_RESET_FAILED:-}"
SECURITY_SLO_MAX_RATE_LIMIT_EXCEEDED="${SECURITY_SLO_MAX_RATE_LIMIT_EXCEEDED:-}"
SECURITY_SLO_MAX_NOTIFICATION_DELIVERY_FAILURE_RATIO="${SECURITY_SLO_MAX_NOTIFICATION_DELIVERY_FAILURE_RATIO:-}"
SECURITY_SLO_MIN_NOTIFICATION_TERMINAL="${SECURITY_SLO_MIN_NOTIFICATION_TERMINAL:-}"

if [ -z "$SECURITY_SLO_LOOKBACK_MINUTES" ]; then
  SECURITY_SLO_LOOKBACK_MINUTES="$(read_env_value "$ENV_FILE" "SECURITY_SLO_LOOKBACK_MINUTES")"
fi
if [ -z "$SECURITY_SLO_MAX_LOGIN_OTP_FAILED" ]; then
  SECURITY_SLO_MAX_LOGIN_OTP_FAILED="$(read_env_value "$ENV_FILE" "SECURITY_SLO_MAX_LOGIN_OTP_FAILED")"
fi
if [ -z "$SECURITY_SLO_MAX_PASSWORD_RESET_FAILED" ]; then
  SECURITY_SLO_MAX_PASSWORD_RESET_FAILED="$(read_env_value "$ENV_FILE" "SECURITY_SLO_MAX_PASSWORD_RESET_FAILED")"
fi
if [ -z "$SECURITY_SLO_MAX_RATE_LIMIT_EXCEEDED" ]; then
  SECURITY_SLO_MAX_RATE_LIMIT_EXCEEDED="$(read_env_value "$ENV_FILE" "SECURITY_SLO_MAX_RATE_LIMIT_EXCEEDED")"
fi
if [ -z "$SECURITY_SLO_MAX_NOTIFICATION_DELIVERY_FAILURE_RATIO" ]; then
  SECURITY_SLO_MAX_NOTIFICATION_DELIVERY_FAILURE_RATIO="$(read_env_value "$ENV_FILE" "SECURITY_SLO_MAX_NOTIFICATION_DELIVERY_FAILURE_RATIO")"
fi
if [ -z "$SECURITY_SLO_MIN_NOTIFICATION_TERMINAL" ]; then
  SECURITY_SLO_MIN_NOTIFICATION_TERMINAL="$(read_env_value "$ENV_FILE" "SECURITY_SLO_MIN_NOTIFICATION_TERMINAL")"
fi

DATABASE_URL="$DATABASE_URL" \
SECURITY_SLO_LOOKBACK_MINUTES="${SECURITY_SLO_LOOKBACK_MINUTES:-60}" \
SECURITY_SLO_MAX_LOGIN_OTP_FAILED="${SECURITY_SLO_MAX_LOGIN_OTP_FAILED:-120}" \
SECURITY_SLO_MAX_PASSWORD_RESET_FAILED="${SECURITY_SLO_MAX_PASSWORD_RESET_FAILED:-60}" \
SECURITY_SLO_MAX_RATE_LIMIT_EXCEEDED="${SECURITY_SLO_MAX_RATE_LIMIT_EXCEEDED:-300}" \
SECURITY_SLO_MAX_NOTIFICATION_DELIVERY_FAILURE_RATIO="${SECURITY_SLO_MAX_NOTIFICATION_DELIVERY_FAILURE_RATIO:-0.25}" \
SECURITY_SLO_MIN_NOTIFICATION_TERMINAL="${SECURITY_SLO_MIN_NOTIFICATION_TERMINAL:-20}" \
node "${SCRIPT_DIR}/check-security-slo.mjs"
